### ISSUE TITLE
pass(1) compatible?

### ISSUE THREAD

**Issue by sewnie** [rnpnr/spm#1]
Hi, i was wondering if spm(1) is a implementation of password store, which has a official implementation written in Bash.

It would be great if spm(1) can be such a replacement for a bash program. Currently, i am using gopass - a password store implementation in Go.

There exists a POSIX sh implementation called [pash](https://github.com/dylanaraps/pash) but it is unmaintained since dylanaraps is on hiatus.

**Comment by rnpnr** [comment]
I believe it is compatible with the directory format of pass. I doubt its compatible with many of pass' "features". For instance there is no automatic git integration and users are expected to know how to use the shell.

My typical usage is (adding passwords):
```bash
pwgen 32 1 | spm add foo/bar
```
and for inserting passwords I have this script bound to `ALT+p` in dwm:
```bash
#!/bin/sh

# types a dmenu selected password
# make sure gpg-agent is running

password=$(spm search . | cut -d '/' -f 5- | dmenu -i -p "Password:") || exit 0
xdotool type --delay 0 $(spm show "$password" | head -1)
```

**Comment by sewnie** [comment]
So i suppose there is subsequently no support for [Android-Password-Store](https://github.com/android-password-store/Android-Password-Store), rather unfortunate.

**Comment by rnpnr** [comment]
I actually use that one just fine. I just meant that if you want to commit these passwords to a git repository you will have to do it yourself.

**Comment by sewnie** [comment]
Well unfortunately I would prefer a git repository so..
